### PR TITLE
Fix exception identifier

### LINKED ISSUE #4: Change exception identifier to avoid confusion with SPDX spec
REUSE specs 2.0 currently refers to the following tags:

- `Valid-License-Identifier` to tag the actual *text of* a license (and `License-Text` to include a copy of its text)
- `SPDX-Exception-Identifier` to tag the actual *text of* an exception (and `Exception-Text` to include a copy of its text)

While the license identifier tag was already changed in order not to clash with the SPDX spec’s own tags, the exception tag was not updated to match it. This can cause confusion.

I would suggest that we also change the license exception tag from `SPDX-Exception-Identifier` to `Valid-Exception-Identifier`.

For more info, see [discussion on SPDX Legal mailing list](https://lists.spdx.org/g/Spdx-legal/topic/change_use_of_spdx/24005641?p=,,,20,0,0,0::recentpostdate%2Fsticky,,,20,2,0,24005641).

### PR DESCRIPTION
**Pull request by silverhook**
Fixes #4

### CODE REVIEW

**Comment by silverhook** [comment]
@jonasob Sounds the right way forward, yes.

**Comment by silverhook** [comment]
@carmenbianca, since we’re now working on 3.0, I think we’re well within the reach of merging this.

**Comment by carmenbianca** [comment]
Should we still do a 2.1?

**Comment by silverhook** [comment]
I think it’s fine to just got for 3.0 now and skip 2.1. There are big changes coming up anyway.

If I followed correctly, the biggest issues were hot-fixed and merged by @jonasob into 2.0 already.

TBH, I think this would be one of the few changes that I would like to still see in 2.x, if we decide to have an update to 2.x still.

**Comment by carmenbianca** [comment]
I don't think we really want to maintain 2.x. Current plans (as I understand) is to leave old versions of the spec in a file in this repository, and to keep only one up-to-date version on the website. If people want an older version, they can find it in the repository.

3.0 should be live quite soon. I think. Depends a little bit on how @mxmehl views the ideal timeline.

**Comment by silverhook** [comment]
Simply deprecating 2.x makes sense to me.

In any case I suggest that before the 3.0 spec launch you leave it in call for comments mode for a reasonable time and promote it in relevant forums. This is a spec, not code – so release often, release early is not the ideal mantra ;)

**Comment by mxmehl** [comment]
> In any case I suggest that before the 3.0 spec launch you leave it in call for comments mode for a reasonable time and promote it in relevant forums. This is a spec, not code – so release often, release early is not the ideal mantra ;)

I agree, and that's basically all opinion I have regarding the timeline – besides the fact that I would love to have it as early as possible :)

**Pull request closed without merging**
